# Generated by Django 5.2.16 on 2026-08-01 14:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="上次登录")),
                ("is_superuser", models.BooleanField(default=False, help_text="指明该用户缺省拥有所有权限。", verbose_name="超级用户状态")),
                ("username", models.CharField(error_messages={"unique": "已存在一位使用该名字的用户。"}, help_text="必填；长度为150个字符或以下；只能包含字母、数字、特殊字符“@”、“.”、“-”和“_”。", max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="用户名")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="名字")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="姓氏")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="电子邮件地址")),
                ("is_staff", models.BooleanField(default=False, help_text="指明用户是否可以登录到这个管理站点。", verbose_name="工作人员状态")),
                ("is_active", models.BooleanField(default=True, help_text="指明用户是否被认为是活跃的。以反选代替删除帐号。", verbose_name="有效")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="加入日期")),
                ("role", models.CharField(choices=[("buyer", "买家"), ("seller", "卖家")], default="buyer", max_length=10, verbose_name="账号类型")),
                ("phone", models.CharField(blank=True, default="", max_length=20, verbose_name="手机号")),
                ("shop_name", models.CharField(blank=True, default="", max_length=100, verbose_name="店铺名称")),
                ("is_seller_approved", models.BooleanField(default=False, verbose_name="卖家是否通过审核")),
                ("groups", models.ManyToManyField(blank=True, help_text="该用户归属的组。一个用户将得到其归属的组的所有权限。", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="组")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="这个用户的特定权限。", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="用户权限")),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("receiver_name", models.CharField(max_length=50, verbose_name="收货人姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("province", models.CharField(blank=True, default="", max_length=50, verbose_name="省份")),
                ("city", models.CharField(blank=True, default="", max_length=50, verbose_name="城市")),
                ("district", models.CharField(blank=True, default="", max_length=50, verbose_name="区县")),
                ("detail", models.CharField(max_length=200, verbose_name="详细地址")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认地址")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to=settings.AUTH_USER_MODEL, verbose_name="所属用户")),
            ],
            options={
                "verbose_name": "收货地址",
                "verbose_name_plural": "收货地址",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100, verbose_name="商品名称")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="商品价格")),
                ("category", models.CharField(choices=[("electronics", "电子产品"), ("clothing", "服装配饰"), ("food", "食品饮料"), ("books", "图书文具"), ("home", "家居生活"), ("sports", "运动户外"), ("beauty", "美妆个护"), ("other", "其他")], db_index=True, default="other", max_length=20, verbose_name="商品类别")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存数量")),
                ("sales_volume", models.PositiveIntegerField(default=0, verbose_name="销量")),
                ("goodsdesc", models.TextField(blank=True, default="", verbose_name="商品描述")),
                ("weight", models.CharField(blank=True, default="", max_length=100, verbose_name="规格/重量")),
                ("imgurl", models.ImageField(blank=True, null=True, upload_to="goods/%Y/%m/", verbose_name="商品图片")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否上架")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goods", to=settings.AUTH_USER_MODEL, verbose_name="所属卖家")),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="收藏时间")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collects", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
                ("goods", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collected_by", to="buy.goods", verbose_name="商品")),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
            },
        ),
        migrations.CreateModel(
            name="BrowseHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("browse_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="浏览时间")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="browse_history", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
                ("goods", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="browse_history", to="buy.goods", verbose_name="浏览商品")),
            ],
            options={
                "verbose_name": "浏览记录",
                "verbose_name_plural": "浏览记录",
                "ordering": ["-browse_time"],
            },
        ),
        migrations.CreateModel(
            name="Goodscar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="商品数量")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="加入购物车时的单价")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="添加时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("goods", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to="buy.goods", verbose_name="商品")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to=settings.AUTH_USER_MODEL, verbose_name="所属用户")),
            ],
            options={
                "verbose_name": "购物车",
                "verbose_name_plural": "购物车",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_no", models.CharField(db_index=True, max_length=32, unique=True, verbose_name="订单号")),
                ("address", models.CharField(max_length=500, verbose_name="收货地址")),
                ("receiver_name", models.CharField(blank=True, default="", max_length=50, verbose_name="收货人")),
                ("receiver_phone", models.CharField(blank=True, default="", max_length=20, verbose_name="收货电话")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="订单总额")),
                ("status", models.CharField(choices=[("unpaid", "待支付"), ("paid", "已支付"), ("shipped", "已发货"), ("completed", "已完成"), ("cancelled", "已取消"), ("refunding", "退款中"), ("refunded", "已退款")], db_index=True, default="unpaid", max_length=20, verbose_name="订单状态")),
                ("refund_reason", models.TextField(blank=True, default="", verbose_name="退款原因")),
                ("status_before_refund", models.CharField(blank=True, default="", max_length=20, verbose_name="申请退款前的状态")),
                ("tracking_no", models.CharField(blank=True, default="", max_length=100, verbose_name="物流单号")),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="支付时间")),
                ("shipped_at", models.DateTimeField(blank=True, null=True, verbose_name="发货时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="取消时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="下单时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sold_orders", to=settings.AUTH_USER_MODEL, verbose_name="卖家")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orders", to=settings.AUTH_USER_MODEL, verbose_name="买家")),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="成交单价")),
                ("number", models.PositiveIntegerField(verbose_name="商品数量")),
                ("goods", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_items", to="buy.goods", verbose_name="商品")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="buy.order", verbose_name="所属订单")),
            ],
            options={
                "verbose_name": "订单商品",
                "verbose_name_plural": "订单商品",
            },
        ),
        migrations.AddIndex(
            model_name="goods",
            index=models.Index(fields=["category", "price"], name="buy_goods_categor_d945a0_idx"),
        ),
        migrations.AddIndex(
            model_name="goods",
            index=models.Index(fields=["seller", "is_active"], name="buy_goods_seller__3ee330_idx"),
        ),
        migrations.AddConstraint(
            model_name="collect",
            constraint=models.UniqueConstraint(fields=("user", "goods"), name="uniq_collect_user_goods"),
        ),
        migrations.AddConstraint(
            model_name="goodscar",
            constraint=models.UniqueConstraint(fields=("user", "goods"), name="uniq_cart_user_goods"),
        ),
    ]
